object:
    # 'M'-瘤体, 'P'-瘤周, 'C'-瘤内
    roi: M
    # 'A'-ADC, 'D'-DWI, 'T'-T2WI
    series: D

classifier:
    # SVM, RF, Bayes, KNN, DT, AB
    model: RF
    # LASSO, RFE, RFC, MI
    filter: LASSO
    # LR, SVM
    RFE_based: SVM

file_path:
    csv: '../data2'
    log: '../output'