object:
    # 'A'-ADC, 'D'-DWI, 'T'-T2WI
    series: T
    # 'M'-瘤体, 'P'-瘤周, 'C'-瘤内
    roi: M

classifier:
    # SVM, RF, Bayes, KNN, LR
    model: RF
    # PCA / LASSO / RFE
    filter: RFE
    # LR, SVM
    RFE_based: SVM

file_path:
    csv: '../data2'
    log: '../output'