object:
    # 'M'-瘤体, 'P'-瘤周, 'C'-瘤内
    roi: C
    # 'A'-ADC, 'D'-DWI, 'T'-T2WI
    series: A

classifier:
    filter: LASSO,RFE
    model: KNN,SVM,Bayes,RF
    RFE_based: LR,SVM

file_path:
    csv: '../data2'
    log: '../output'